[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "niimetric"
version = "0.1.9"
description = "Evaluate image quality metrics (SSIM, MAE, LPIPS, PSNR) and add realistic artifacts/augmentations for NIfTI images"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Jinghang Li", email = "jinghang.li@pitt.edu"}
]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = ["nifti", "mri", "image-quality", "ssim", "psnr", "lpips", "mae", "augmentation", "torchio", "noise"]
dependencies = [
    "scipy",
    "nibabel>=4.0.0",
    "numpy>=1.20.0",
    "scikit-image>=0.19.0",
    "torch>=1.9.0",
    "lpips>=0.1.4",
    "torchio>=0.19.0",
]

[project.scripts]
niimetric = "niimetric.cli:main"
noise_robust = "niimetric.noise_robust_cli:main"
noise = "niimetric.noise_cli:main"
blur = "niimetric.blur_cli:main"
bias = "niimetric.inhomogeneity_cli:main"
motion = "niimetric.motion_cli:main"
ghost = "niimetric.ghosting_cli:main"
grappa = "niimetric.grappa_cli:main"

[project.urls]
Homepage = "https://github.com/jinghangli98/niimetric"
Repository = "https://github.com/jinghangli98/niimetric"

[tool.setuptools.packages.find]
where = ["src"]
